// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Speak
{
    internal sealed partial class Vsix
    {
        public const string Id = "Speak.899ea22a-c6e2-43f6-b3eb-50a3713c4df7";
        public const string Name = "Voice Typing";
        public const string Description = @"Hold down the CTRL key to speak to Visual Studio. Makes it easy to prompt Copilot or write code comments using your voice";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "voice, ai, copilot, speech";
    }
}
